name: labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches: [dev]

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # actions/labeler@v6.1.0
        with:
          sync-labels: true
